version: '3.8'
services:
  mongo-primary:
    image: mongo:4.4
    container_name: mongo-primary
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-primary-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

  mongo-secondary1:
    image: mongo:4.4
    container_name: mongo-secondary1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-sec1-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster

  mongo-secondary2:
    image: mongo:4.4
    container_name: mongo-secondary2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-sec2-data:/data/db
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster

volumes:
  mongo-primary-data:
  mongo-sec1-data:
  mongo-sec2-data:

networks:
  mongo-cluster:
    driver: bridge
